version: '3'
services:
  frontend:
       image: drupal
       ports:
       -80:80
       network:
       -jenkinit
  Backend:
      image: postgres
      environment:
      POSTGRES_PASSWORD=123456
      network:
      -jenkinit
network:
  jenkinit:
