version: '3'
services:
  frontend:
       image: drupal
       ports:
       - 80:80
       networks:
       - jenkinit
  Backend:
      image: postgres
      environment:
      POSTGRES_PASSWORD=123456
      networks:
      - jenkinit
networks:
  jenkinit:
