version: '3'
services : 
  frontend:
    image: drupal 
    ports:  
    - 80:80
    networks: 
    - jenkinet
  Backend:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=123456
    networks:
    - jenkinet
  networks:
   jenkinet:

