version: '3'
services : 
  frontend:
    image: drupal 
    ports:  
    - 80:80
    networks: 
    - jenknet
  Backend:
    image: postgres
    environment:
    - POSTGRES_PASSWOED=123456
    networks:
    - jenknet
  networks:
   jenknet:

